dist: xenial

language: node_js
node_js: 10

stages:
  - build
  - deploy
    if: branch = master
    env: TARGET=html5

env:
  - TARGET=linux --compile
  - TARGET=linux-hl --compile
  - TARGET=html5
  # - TARGET=osx --compile
  # - TARGET=osx-hl --compile

jobs:
  include:
    - stage: build
      script: node Kha/make $TARGET
    - stage: deploy
      script: ./deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  committer_from_gh: true
  local_dir: build/html5
  on:
    branch: master
