dist: xenial

language: node_js
node_js: 10

env:
  - BUILD_TARGET=linux BUILD_TARGET_COMPILE=--compile
  # - TARGET=linux-hl --compile
  - BUILD_TARGET=html5 BUILD_TARGET_COMPILE=""
  # - TARGET=osx --compile
  # - TARGET=osx-hl --compile

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script: node Kha/make $BUILD_TARGET $BUILD_TARGET_COMPILE
    # - stage: deploy
      # script: ./deploy
      # env: TARGET = html5

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   committer_from_gh: true
#   local_dir: build/html5
#   on:
#     branch: master
