dist: xenial
addons:
  apt:
    packages:
    - libxinerama-dev
    - libasound2-dev
    - mesa-common-dev
    - libgl-dev
    - libxi-dev

language: node_js
node_js: 10

env:
  - BUILD_TARGET=linux --compile
  - BUILD_TARGET=linux-hl --compile
  - BUILD_TARGET=html5
  # - BUILD_TARGET=osx --compile
  # - BUILD_TARGET=osx-hl --compile

stages:
  - build
  # - name: deploy
    # if: branch = master

jobs:
  include:
    - stage: build
      script: node Kha/make $BUILD_TARGET $BUILD_TARGET_COMPILE
    # - stage: deploy
      # script: ./deploy
      # env: TARGET = html5

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   committer_from_gh: true
#   local_dir: build/html5
#   on:
#     branch: master
