dist: xenial
addons:
  apt:
    packages:
    - libxinerama-dev
    - libasound2-dev
    - mesa-common-dev
    - libgl-dev
    - libxi-dev

language: node_js
node_js: 10

env:
  # - BUILD_TARGET=linux BUILD_OPTS="--compile"
  - BUILD_TARGET=linux-hl BUILD_OPTS="--compile"
  - BUILD_TARGET=html5 BUILD_OPTS=""
  # - BUILD_TARGET=osx --compile
  # - BUILD_TARGET=osx-hl --compile

script:
  - node Kha/make $BUILD_TARGET $BUILD_OPTS

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  committer_from_gh: true
  local_dir: build/html5
  on:
    branch: master
    condition: $BUILD_TARGET = html5

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/$BUILD_TARGET/**/*
  skip_cleanup: true
  on:
    condition: $BUILD_TARGET = linux
