image: Visual Studio 2017

version: 0.0.{build}

platform:
  - x64
  # - x86

environment:
  matrix:
  - platform_name: windows
  # - platform_name: windows-hl

before_build:
  - git submodule update --init --recursive
  - git clone https://github.com/Kode/nodejs_bin.git
  - nodejs_bin\node.exe Kha\make %platform_name% --compile --visualstudio vs2017

build:
  project: build\%platform_name%-build\ruz.sln
  verbosity: minimal

after_build:
  - 7z a royal-ur.zui-client-win-{build}.zip $APPVEYOR_BUILD_FOLDER%\build\windows\*.*

artifacts:
  - path: royal-ur.zui-client-win-{build}.zip
    name: royal-ur.zui-client-win-{build}
